name : Exo 2  CI
on:
  pull_request:
    branches: [ "Exo_B" ]
    paths:
        - '**.yml'
        - '!tests/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Véfication des fichiers yaml"